<?php

namespace Database\Seeders;

use App\Models\Balita;
use App\Models\KepalaKeluarga;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BalitaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kepalaKeluarga = KepalaKeluarga::all();

        // Data Balita 1
        Balita::create([
            'kepala_keluarga_id' => $kepalaKeluarga->first()->id,
            'nama_bayi' => 'Muhammad Rizki',
            'nik' => '3501123456789013',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2023-08-15',
            'berat_badan_lahir' => 3.2,
            'panjang_badan_lahir' => 50.0,
            'nama_ortu' => 'Budi Santoso & Dewi Lestari',
            'alamat' => 'Jl. Merdeka No. 123',
            'no_hp' => '081234567890',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'umur' => 20,
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 12.5,
            'naik_tidak_naik' => 'Naik',
            'status_bb_u' => 'Normal',
            'panjang_badan' => 84.0,
            'status_pb_u' => 'Normal',
            'status_bb_pb' => 'Baik',
            'lingkar_lengan' => 16.5,
            'status_lila' => 'Normal',
            'lingkar_kepala' => 48.0,
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'perkembangan' => 'Lengkap',
            'asi_eksklusif' => 'Tidak',
            'mpasi' => 'Ya',
            'imunisasi' => 'BCG, Polio, DPT 1',
            'vitamin_a' => 'Ya',
            'obat_cacing' => 'Ya',
            'mt_pangan' => 'Ya',
            'edukasi' => 'Edukasi nutrisi dan stimulasi perkembangan',
            'catatan_kesehatan' => 'Pertumbuhan baik, sesuai kurva WHO',
            'rujukan' => 'Tidak',
        ]);

        // Data Balita 2
        Balita::create([
            'kepala_keluarga_id' => $kepalaKeluarga->skip(1)->first()->id,
            'nama_bayi' => 'Siti Nurhaliza',
            'nik' => '3501234567890124',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2022-05-20',
            'berat_badan_lahir' => 3.0,
            'panjang_badan_lahir' => 49.5,
            'nama_ortu' => 'Ahmad Wijaya & Nur Cahaya',
            'alamat' => 'Jl. Ahmad Yani No. 45',
            'no_hp' => '081234567891',
            'dusun' => 'Dusun 2',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'umur' => 35,
            'waktu_kunjungan' => 'Sore',
            'berat_badan' => 15.0,
            'naik_tidak_naik' => 'Naik',
            'status_bb_u' => 'Normal',
            'panjang_badan' => 95.0,
            'status_pb_u' => 'Normal',
            'status_bb_pb' => 'Baik',
            'lingkar_lengan' => 17.5,
            'status_lila' => 'Normal',
            'lingkar_kepala' => 50.0,
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'perkembangan' => 'Lengkap',
            'asi_eksklusif' => 'Tidak',
            'mpasi' => 'Ya',
            'imunisasi' => 'BCG, Polio, DPT 1-2, Campak',
            'vitamin_a' => 'Ya',
            'obat_cacing' => 'Ya',
            'mt_pangan' => 'Ya',
            'edukasi' => 'Edukasi stimulasi motorik kasar dan halus',
            'catatan_kesehatan' => 'Aktif dan ceria, pertumbuhan optimal',
            'rujukan' => 'Tidak',
        ]);

        // Data Balita 3
        Balita::create([
            'kepala_keluarga_id' => $kepalaKeluarga->skip(2)->first()->id,
            'nama_bayi' => 'Raka Pratama Jr',
            'nik' => '3501345678901235',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2024-02-10',
            'berat_badan_lahir' => 3.4,
            'panjang_badan_lahir' => 51.0,
            'nama_ortu' => 'Raka Pratama & Sinta Kusuma',
            'alamat' => 'Jl. Diponegoro No. 78',
            'no_hp' => '081234567892',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'umur' => 14,
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 7.5,
            'naik_tidak_naik' => 'Naik',
            'status_bb_u' => 'Normal',
            'panjang_badan' => 64.0,
            'status_pb_u' => 'Normal',
            'status_bb_pb' => 'Baik',
            'lingkar_lengan' => 14.0,
            'status_lila' => 'Normal',
            'lingkar_kepala' => 42.0,
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'perkembangan' => 'Lengkap',
            'asi_eksklusif' => 'Ya',
            'mpasi' => 'Belum',
            'imunisasi' => 'BCG, Polio 0-3',
            'vitamin_a' => 'Ya',
            'obat_cacing' => 'Ya',
            'mt_pangan' => 'Ya',
            'edukasi' => 'ASI eksklusif, persiapan MPASI',
            'catatan_kesehatan' => 'Bayi sehat, beratnya sesuai standar',
            'rujukan' => 'Tidak',
        ]);

        // RIWAYAT PEMERIKSAAN - DUPLIKAT DATA (untuk tracking history)
        // Balita 1 - Pemeriksaan ke-2 (lebih awal)
        Balita::create([
            'kepala_keluarga_id' => $kepalaKeluarga->first()->id,
            'nama_bayi' => 'Muhammad Rizki',
            'nik' => '3501123456789013',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2023-08-15',
            'berat_badan_lahir' => 3.2,
            'panjang_badan_lahir' => 50.0,
            'nama_ortu' => 'Budi Santoso & Dewi Lestari',
            'alamat' => 'Jl. Merdeka No. 123',
            'no_hp' => '081234567890',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'umur' => 18,
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 11.8,
            'naik_tidak_naik' => 'Naik',
            'status_bb_u' => 'Normal',
            'panjang_badan' => 82.0,
            'status_pb_u' => 'Normal',
            'status_bb_pb' => 'Baik',
            'lingkar_lengan' => 16.0,
            'status_lila' => 'Normal',
            'lingkar_kepala' => 47.5,
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'perkembangan' => 'Lengkap',
            'asi_eksklusif' => 'Tidak',
            'mpasi' => 'Ya',
            'imunisasi' => 'BCG, Polio, DPT 1',
            'vitamin_a' => 'Ya',
            'obat_cacing' => 'Ya',
            'mt_pangan' => 'Ya',
            'edukasi' => 'Edukasi nutrisi dan stimulasi perkembangan',
            'catatan_kesehatan' => 'Pertumbuhan baik, berat naik 0.7 kg dari bulan lalu',
            'rujukan' => 'Tidak',
        ]);

        // Balita 1 - Pemeriksaan ke-3 (lebih lama lagi)
        Balita::create([
            'kepala_keluarga_id' => $kepalaKeluarga->first()->id,
            'nama_bayi' => 'Muhammad Rizki',
            'nik' => '3501123456789013',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2023-08-15',
            'berat_badan_lahir' => 3.2,
            'panjang_badan_lahir' => 50.0,
            'nama_ortu' => 'Budi Santoso & Dewi Lestari',
            'alamat' => 'Jl. Merdeka No. 123',
            'no_hp' => '081234567890',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'umur' => 16,
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 11.0,
            'naik_tidak_naik' => 'Naik',
            'status_bb_u' => 'Normal',
            'panjang_badan' => 80.5,
            'status_pb_u' => 'Normal',
            'status_bb_pb' => 'Baik',
            'lingkar_lengan' => 15.5,
            'status_lila' => 'Normal',
            'lingkar_kepala' => 47.0,
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'perkembangan' => 'Monitor',
            'asi_eksklusif' => 'Tidak',
            'mpasi' => 'Ya',
            'imunisasi' => 'BCG, Polio, DPT 1',
            'vitamin_a' => 'Ya',
            'obat_cacing' => 'Ya',
            'mt_pangan' => 'Ya',
            'edukasi' => 'Edukasi nutrisi',
            'catatan_kesehatan' => 'Pemeriksaan kedua, perkembangan normal',
            'rujukan' => 'Tidak',
        ]);

        // Balita 2 - Pemeriksaan ke-2
        Balita::create([
            'kepala_keluarga_id' => $kepalaKeluarga->skip(1)->first()->id,
            'nama_bayi' => 'Siti Nurhaliza',
            'nik' => '3501234567890124',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2022-05-20',
            'berat_badan_lahir' => 3.0,
            'panjang_badan_lahir' => 49.5,
            'nama_ortu' => 'Ahmad Wijaya & Nur Cahaya',
            'alamat' => 'Jl. Ahmad Yani No. 45',
            'no_hp' => '081234567891',
            'dusun' => 'Dusun 2',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'umur' => 33,
            'waktu_kunjungan' => 'Sore',
            'berat_badan' => 14.5,
            'naik_tidak_naik' => 'Naik',
            'status_bb_u' => 'Normal',
            'panjang_badan' => 93.5,
            'status_pb_u' => 'Normal',
            'status_bb_pb' => 'Baik',
            'lingkar_lengan' => 17.0,
            'status_lila' => 'Normal',
            'lingkar_kepala' => 49.8,
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'perkembangan' => 'Lengkap',
            'asi_eksklusif' => 'Tidak',
            'mpasi' => 'Ya',
            'imunisasi' => 'BCG, Polio, DPT 1-2, Campak',
            'vitamin_a' => 'Ya',
            'obat_cacing' => 'Ya',
            'mt_pangan' => 'Ya',
            'edukasi' => 'Edukasi stimulasi motorik',
            'catatan_kesehatan' => 'Aktif, berat naik 0.5 kg',
            'rujukan' => 'Tidak',
        ]);

        // Balita 3 - Pemeriksaan ke-2 (lebih awal)
        Balita::create([
            'kepala_keluarga_id' => $kepalaKeluarga->skip(2)->first()->id,
            'nama_bayi' => 'Raka Pratama Jr',
            'nik' => '3501345678901235',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2024-02-10',
            'berat_badan_lahir' => 3.4,
            'panjang_badan_lahir' => 51.0,
            'nama_ortu' => 'Raka Pratama & Sinta Kusuma',
            'alamat' => 'Jl. Diponegoro No. 78',
            'no_hp' => '081234567892',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'umur' => 12,
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 6.8,
            'naik_tidak_naik' => 'Naik',
            'status_bb_u' => 'Normal',
            'panjang_badan' => 62.5,
            'status_pb_u' => 'Normal',
            'status_bb_pb' => 'Baik',
            'lingkar_lengan' => 13.8,
            'status_lila' => 'Normal',
            'lingkar_kepala' => 41.5,
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'perkembangan' => 'Lengkap',
            'asi_eksklusif' => 'Ya',
            'mpasi' => 'Belum',
            'imunisasi' => 'BCG, Polio 0-2',
            'vitamin_a' => 'Ya',
            'obat_cacing' => 'Ya',
            'mt_pangan' => 'Ya',
            'edukasi' => 'ASI eksklusif',
            'catatan_kesehatan' => 'Bayi sehat, berat naik normal',
            'rujukan' => 'Tidak',
        ]);
    }
}
