<?php

namespace Database\Seeders;

use App\Models\Dewasa;
use App\Models\KepalaKeluarga;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DewasaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kepalaKeluarga = KepalaKeluarga::all();

        // Data Dewasa 1 - Pemeriksaan pertama
        Dewasa::create([
            'kepala_keluarga_id' => $kepalaKeluarga->first()->id,
            'nama' => 'Bapak Suryanto',
            'nik' => '3501111234567890',
            'tanggal_lahir' => '1975-06-10',
            'umur' => '50',
            'alamat' => 'Jl. Merdeka No. 123',
            'no_hp' => '081234567890',
            'status_perkawinan' => 'Kawin',
            'pekerjaan' => 'Petani',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'riwayat_keluarga' => 'Ayah diabetes, ibu hipertensi',
            'riwayat_diri' => 'Sehat, pernah flu',
            'merokok' => 'Ya',
            'konsumsi_gula' => 'Ya',
            'konsumsi_garam' => 'Ya',
            'konsumsi_lemak' => 'Tidak',
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 75.5,
            'tinggi_badan' => 168.0,
            'imt' => 'Gemuk',
            'lingkar_perut' => 95.0,
            'sistole' => 135,
            'diastole' => 85,
            'tekanan_darah_status' => 'Tinggi',
            'gula_darah' => 'Tinggi',
            'mata_kanan' => 'Normal',
            'mata_kiri' => 'Normal',
            'telinga_kanan' => 'Normal',
            'telinga_kiri' => 'Normal',
            'jenis_kelamin' => 'Laki-laki',
            'usia_kategori' => '50-59',
            'skor_merokok' => 3,
            'napas_berat' => 'Ya',
            'dahak' => 'Tidak',
            'batuk' => 'Ya',
            'aktivitas_terganggu' => 'Tidak',
            'pemeriksaan_sebelumnya' => 'Ya',
            'skor_puma' => 6,
            'batuk_tbc' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'edukasi' => 'Program berhenti merokok, diet sehat',
            'rujukan' => 'Rujuk ke poli paru',
        ]);

        // Data Dewasa 2 - Pemeriksaan pertama
        Dewasa::create([
            'kepala_keluarga_id' => $kepalaKeluarga->skip(1)->first()->id,
            'nama' => 'Ibu Siti Nurhaliza',
            'nik' => '3501111234567891',
            'tanggal_lahir' => '1978-09-22',
            'umur' => '47',
            'alamat' => 'Jl. Ahmad Yani No. 45',
            'no_hp' => '081234567891',
            'status_perkawinan' => 'Kawin',
            'pekerjaan' => 'Ibu Rumah Tangga',
            'dusun' => 'Dusun 2',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'riwayat_keluarga' => 'Ibu hipertensi',
            'riwayat_diri' => 'Sehat',
            'merokok' => 'Tidak',
            'konsumsi_gula' => 'Ya',
            'konsumsi_garam' => 'Ya',
            'konsumsi_lemak' => 'Ya',
            'waktu_kunjungan' => 'Sore',
            'berat_badan' => 68.0,
            'tinggi_badan' => 156.0,
            'imt' => 'Gemuk',
            'lingkar_perut' => 92.0,
            'sistole' => 128,
            'diastole' => 82,
            'tekanan_darah_status' => 'Tinggi',
            'gula_darah' => 'Normal',
            'mata_kanan' => 'Normal',
            'mata_kiri' => 'Normal',
            'telinga_kanan' => 'Normal',
            'telinga_kiri' => 'Normal',
            'jenis_kelamin' => 'Perempuan',
            'usia_kategori' => '40-49',
            'skor_merokok' => 0,
            'napas_berat' => 'Tidak',
            'dahak' => 'Tidak',
            'batuk' => 'Tidak',
            'aktivitas_terganggu' => 'Tidak',
            'pemeriksaan_sebelumnya' => 'Tidak',
            'skor_puma' => 0,
            'batuk_tbc' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'edukasi' => 'Program diet, olahraga',
            'rujukan' => 'Rujuk ke poli dalam',
        ]);

        // Data Dewasa 3 - Pemeriksaan pertama
        Dewasa::create([
            'kepala_keluarga_id' => $kepalaKeluarga->skip(2)->first()->id,
            'nama' => 'Pak Haryanto',
            'nik' => '3501111234567892',
            'tanggal_lahir' => '1982-02-14',
            'umur' => '43',
            'alamat' => 'Jl. Diponegoro No. 78',
            'no_hp' => '081234567892',
            'status_perkawinan' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'riwayat_keluarga' => 'Tidak ada',
            'riwayat_diri' => 'Sehat, alergi debu',
            'merokok' => 'Tidak',
            'konsumsi_gula' => 'Tidak',
            'konsumsi_garam' => 'Tidak',
            'konsumsi_lemak' => 'Tidak',
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 70.0,
            'tinggi_badan' => 172.0,
            'imt' => 'Normal',
            'lingkar_perut' => 85.0,
            'sistole' => 120,
            'diastole' => 78,
            'tekanan_darah_status' => 'Normal',
            'gula_darah' => 'Normal',
            'mata_kanan' => 'Normal',
            'mata_kiri' => 'Normal',
            'telinga_kanan' => 'Normal',
            'telinga_kiri' => 'Normal',
            'jenis_kelamin' => 'Laki-laki',
            'usia_kategori' => '40-49',
            'skor_merokok' => 0,
            'napas_berat' => 'Tidak',
            'dahak' => 'Tidak',
            'batuk' => 'Tidak',
            'aktivitas_terganggu' => 'Tidak',
            'pemeriksaan_sebelumnya' => 'Tidak',
            'skor_puma' => 0,
            'batuk_tbc' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'edukasi' => 'Edukasi gaya hidup sehat',
            'rujukan' => 'Tidak',
        ]);

        // RIWAYAT PEMERIKSAAN - DUPLIKAT DATA
        // Dewasa 1 - Pemeriksaan ke-2 (follow-up 2 bulan)
        Dewasa::create([
            'kepala_keluarga_id' => $kepalaKeluarga->first()->id,
            'nama' => 'Bapak Suryanto',
            'nik' => '3501111234567890',
            'tanggal_lahir' => '1975-06-10',
            'umur' => '50',
            'alamat' => 'Jl. Merdeka No. 123',
            'no_hp' => '081234567890',
            'status_perkawinan' => 'Kawin',
            'pekerjaan' => 'Petani',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'riwayat_keluarga' => 'Ayah diabetes, ibu hipertensi',
            'riwayat_diri' => 'Sehat',
            'merokok' => 'Tidak',
            'konsumsi_gula' => 'Ya',
            'konsumsi_garam' => 'Ya',
            'konsumsi_lemak' => 'Tidak',
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 73.0,
            'tinggi_badan' => 168.0,
            'imt' => 'Gemuk',
            'lingkar_perut' => 92.0,
            'sistole' => 130,
            'diastole' => 82,
            'tekanan_darah_status' => 'Tinggi',
            'gula_darah' => 'Tinggi',
            'mata_kanan' => 'Normal',
            'mata_kiri' => 'Normal',
            'telinga_kanan' => 'Normal',
            'telinga_kiri' => 'Normal',
            'jenis_kelamin' => 'Laki-laki',
            'usia_kategori' => '50-59',
            'skor_merokok' => 0,
            'napas_berat' => 'Ya',
            'dahak' => 'Tidak',
            'batuk' => 'Ya',
            'aktivitas_terganggu' => 'Tidak',
            'pemeriksaan_sebelumnya' => 'Ya',
            'skor_puma' => 4,
            'batuk_tbc' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'edukasi' => 'Program berhenti merokok lanjutan',
            'rujukan' => 'Tidak',
        ]);

        // Dewasa 2 - Pemeriksaan ke-2 (follow-up 3 bulan)
        Dewasa::create([
            'kepala_keluarga_id' => $kepalaKeluarga->skip(1)->first()->id,
            'nama' => 'Ibu Siti Nurhaliza',
            'nik' => '3501111234567891',
            'tanggal_lahir' => '1978-09-22',
            'umur' => '47',
            'alamat' => 'Jl. Ahmad Yani No. 45',
            'no_hp' => '081234567891',
            'status_perkawinan' => 'Kawin',
            'pekerjaan' => 'Ibu Rumah Tangga',
            'dusun' => 'Dusun 2',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'riwayat_keluarga' => 'Ibu hipertensi',
            'riwayat_diri' => 'Sehat',
            'merokok' => 'Tidak',
            'konsumsi_gula' => 'Ya',
            'konsumsi_garam' => 'Ya',
            'konsumsi_lemak' => 'Tidak',
            'waktu_kunjungan' => 'Sore',
            'berat_badan' => 65.5,
            'tinggi_badan' => 156.0,
            'imt' => 'Normal',
            'lingkar_perut' => 88.0,
            'sistole' => 122,
            'diastole' => 80,
            'tekanan_darah_status' => 'Normal',
            'gula_darah' => 'Normal',
            'mata_kanan' => 'Normal',
            'mata_kiri' => 'Normal',
            'telinga_kanan' => 'Normal',
            'telinga_kiri' => 'Normal',
            'jenis_kelamin' => 'Perempuan',
            'usia_kategori' => '40-49',
            'skor_merokok' => 0,
            'napas_berat' => 'Tidak',
            'dahak' => 'Tidak',
            'batuk' => 'Tidak',
            'aktivitas_terganggu' => 'Tidak',
            'pemeriksaan_sebelumnya' => 'Tidak',
            'skor_puma' => 0,
            'batuk_tbc' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'edukasi' => 'Program diet berhasil, berat turun 2.5 kg',
            'rujukan' => 'Tidak',
        ]);
    }
}
