<?php

namespace Database\Seeders;

use App\Models\Remaja;
use App\Models\KepalaKeluarga;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RemajaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kepalaKeluarga = KepalaKeluarga::all();

        // Data Remaja 1 - Pemeriksaan pertama
        Remaja::create([
            'kepala_keluarga_id' => $kepalaKeluarga->first()->id,
            'nama_anak' => 'Anisa Putri',
            'nik' => '3501123456789014',
            'tanggal_lahir' => '2010-03-15',
            'jenis_kelamin' => 'Perempuan',
            'nama_ortu' => 'Budi Santoso & Dewi Lestari',
            'alamat' => 'Jl. Merdeka No. 123',
            'no_hp' => '081234567890',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'riwayat_keluarga' => 'Tidak ada',
            'riwayat_diri' => 'Sehat',
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 48.0,
            'tinggi_badan' => 162.0,
            'imt_status' => 'Normal',
            'lingkar_perut' => 72.0,
            'sistole' => 110,
            'diastole' => 70,
            'tekanan_darah_status' => 'Normal',
            'gula_darah' => 'Normal',
            'hemoglobin' => '12.5',
            'anemia' => 'Tidak',
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'masalah_rumah' => 'Tidak',
            'masalah_pendidikan' => 'Tidak',
            'masalah_makan' => 'Tidak',
            'masalah_aktivitas' => 'Tidak',
            'masalah_obat' => 'Tidak',
            'masalah_seksual' => 'Tidak',
            'masalah_emosi' => 'Tidak',
            'masalah_keamanan' => 'Tidak',
            'edukasi' => 'Edukasi kesehatan reproduksi dan NAPZA',
            'rujukan' => 'Tidak',
        ]);

        // Data Remaja 2 - Pemeriksaan pertama
        Remaja::create([
            'kepala_keluarga_id' => $kepalaKeluarga->skip(1)->first()->id,
            'nama_anak' => 'Budi Pratama',
            'nik' => '3501234567890125',
            'tanggal_lahir' => '2009-07-20',
            'jenis_kelamin' => 'Laki-laki',
            'nama_ortu' => 'Ahmad Wijaya & Nur Cahaya',
            'alamat' => 'Jl. Ahmad Yani No. 45',
            'no_hp' => '081234567891',
            'dusun' => 'Dusun 2',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'riwayat_keluarga' => 'Ayah hipertensi',
            'riwayat_diri' => 'Sehat, alergi makanan laut',
            'waktu_kunjungan' => 'Sore',
            'berat_badan' => 62.0,
            'tinggi_badan' => 172.0,
            'imt_status' => 'Normal',
            'lingkar_perut' => 80.0,
            'sistole' => 115,
            'diastole' => 75,
            'tekanan_darah_status' => 'Normal',
            'gula_darah' => 'Normal',
            'hemoglobin' => '13.0',
            'anemia' => 'Tidak',
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'masalah_rumah' => 'Tidak',
            'masalah_pendidikan' => 'Tidak',
            'masalah_makan' => 'Tidak',
            'masalah_aktivitas' => 'Tidak',
            'masalah_obat' => 'Tidak',
            'masalah_seksual' => 'Tidak',
            'masalah_emosi' => 'Tidak',
            'masalah_keamanan' => 'Tidak',
            'edukasi' => 'Edukasi gaya hidup sehat dan pencegahan penyakit',
            'rujukan' => 'Tidak',
        ]);

        // Data Remaja 3 - Pemeriksaan pertama
        Remaja::create([
            'kepala_keluarga_id' => $kepalaKeluarga->skip(2)->first()->id,
            'nama_anak' => 'Citra Dewi',
            'nik' => '3501345678901236',
            'tanggal_lahir' => '2011-11-05',
            'jenis_kelamin' => 'Perempuan',
            'nama_ortu' => 'Raka Pratama & Sinta Kusuma',
            'alamat' => 'Jl. Diponegoro No. 78',
            'no_hp' => '081234567892',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'riwayat_keluarga' => 'Tidak ada',
            'riwayat_diri' => 'Sehat',
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 46.0,
            'tinggi_badan' => 158.0,
            'imt_status' => 'Normal',
            'lingkar_perut' => 70.0,
            'sistole' => 105,
            'diastole' => 68,
            'tekanan_darah_status' => 'Normal',
            'gula_darah' => 'Normal',
            'hemoglobin' => '12.0',
            'anemia' => 'Tidak',
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'masalah_rumah' => 'Tidak',
            'masalah_pendidikan' => 'Tidak',
            'masalah_makan' => 'Tidak',
            'masalah_aktivitas' => 'Tidak',
            'masalah_obat' => 'Tidak',
            'masalah_seksual' => 'Tidak',
            'masalah_emosi' => 'Tidak',
            'masalah_keamanan' => 'Tidak',
            'edukasi' => 'Edukasi kesehatan mental dan aktivitas fisik',
            'rujukan' => 'Tidak',
        ]);

        // RIWAYAT PEMERIKSAAN - DUPLIKAT DATA
        // Remaja 1 - Pemeriksaan ke-2
        Remaja::create([
            'kepala_keluarga_id' => $kepalaKeluarga->first()->id,
            'nama_anak' => 'Anisa Putri',
            'nik' => '3501123456789014',
            'tanggal_lahir' => '2010-03-15',
            'jenis_kelamin' => 'Perempuan',
            'nama_ortu' => 'Budi Santoso & Dewi Lestari',
            'alamat' => 'Jl. Merdeka No. 123',
            'no_hp' => '081234567890',
            'dusun' => 'Dusun 1',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'riwayat_keluarga' => 'Tidak ada',
            'riwayat_diri' => 'Sehat',
            'waktu_kunjungan' => 'Pagi',
            'berat_badan' => 49.5,
            'tinggi_badan' => 163.0,
            'imt_status' => 'Normal',
            'lingkar_perut' => 73.0,
            'sistole' => 112,
            'diastole' => 71,
            'tekanan_darah_status' => 'Normal',
            'gula_darah' => 'Normal',
            'hemoglobin' => '12.6',
            'anemia' => 'Tidak',
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'masalah_rumah' => 'Tidak',
            'masalah_pendidikan' => 'Tidak',
            'masalah_makan' => 'Tidak',
            'masalah_aktivitas' => 'Tidak',
            'masalah_obat' => 'Tidak',
            'masalah_seksual' => 'Tidak',
            'masalah_emosi' => 'Tidak',
            'masalah_keamanan' => 'Tidak',
            'edukasi' => 'Follow-up kesehatan reproduksi',
            'rujukan' => 'Tidak',
        ]);

        // Remaja 2 - Pemeriksaan ke-2
        Remaja::create([
            'kepala_keluarga_id' => $kepalaKeluarga->skip(1)->first()->id,
            'nama_anak' => 'Budi Pratama',
            'nik' => '3501234567890125',
            'tanggal_lahir' => '2009-07-20',
            'jenis_kelamin' => 'Laki-laki',
            'nama_ortu' => 'Ahmad Wijaya & Nur Cahaya',
            'alamat' => 'Jl. Ahmad Yani No. 45',
            'no_hp' => '081234567891',
            'dusun' => 'Dusun 2',
            'desa' => 'Sukodono',
            'kecamatan' => 'Sukodono',
            'riwayat_keluarga' => 'Ayah hipertensi',
            'riwayat_diri' => 'Sehat, alergi makanan laut',
            'waktu_kunjungan' => 'Sore',
            'berat_badan' => 64.0,
            'tinggi_badan' => 173.0,
            'imt_status' => 'Normal',
            'lingkar_perut' => 82.0,
            'sistole' => 117,
            'diastole' => 76,
            'tekanan_darah_status' => 'Normal',
            'gula_darah' => 'Normal',
            'hemoglobin' => '13.1',
            'anemia' => 'Tidak',
            'batuk' => 'Tidak',
            'demam' => 'Tidak',
            'bb_turun' => 'Tidak',
            'kontak_tbc' => 'Tidak',
            'masalah_rumah' => 'Tidak',
            'masalah_pendidikan' => 'Tidak',
            'masalah_makan' => 'Tidak',
            'masalah_aktivitas' => 'Tidak',
            'masalah_obat' => 'Tidak',
            'masalah_seksual' => 'Tidak',
            'masalah_emosi' => 'Tidak',
            'masalah_keamanan' => 'Tidak',
            'edukasi' => 'Follow-up gaya hidup sehat',
            'rujukan' => 'Tidak',
        ]);
    }
}
